## Part 1- Data Coding and Merging

In [1]:
#Import Libraries

import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Import NHL Team Data and Display
NHL_Team=pd.read_csv("NHL_team.csv")
display(NHL_Team)

,Unnamed: 0,tid,name,tname,lname,tricode,abbr,sname
0,1,1,Toronto Maple Leafs,Maple Leafs,Toronto,TOR,TOR,Toronto
1,2,2,Montréal Canadiens,Canadiens,Montréal,MTL,MTL,Montréal
2,3,4,Winnipeg Jets,Jets,Winnipeg,WPG,WPG,Winnipeg
3,4,5,Washington Capitals,Capitals,Washington,WSH,WSH,Washington
4,5,6,Chicago Blackhawks,Blackhawks,Chicago,CHI,CHI,Chicago
5,6,7,St. Louis Blues,Blues,St. Louis,STL,STL,St Louis
6,7,8,Pittsburgh Penguins,Penguins,Pittsburgh,PIT,PIT,Pittsburgh
7,8,10,Edmonton Oilers,Oilers,Edmonton,EDM,EDM,Edmonton
8,9,11,Calgary Flames,Flames,Calgary,CGY,CGY,Calgary
9,10,14,Philadelphia Flyers,Flyers,Philadelphia,PHI,PHI,Philadelphia
10,11,16,San Jose Sharks,Sharks,San Jose,SJS,SJS,San Jose
11,12,17,Buffalo Sabres,Sabres,Buffalo,BUF,BUF,Buffalo
12,13,18,Detroit Red Wings,Red Wings,Detroit,DET,DET,Detroit
13,14,19,Nashville Predators,Predators,Nashville,NSH,NSH,Nashville
14,15,20,Boston Bruins,Bruins,Boston,BOS,BOS,Boston
15,16,21,Anaheim Ducks,Ducks,Anaheim,ANA,ANA,Anaheim
16,17,22,Colorado Avalanche,Avalanche,Colorado,COL,COL,Colorado
17,18,25,Tampa Bay Lightning,Lightning,Tampa Bay,TBL,TBL,Tampa Bay
18,19,28,New York Rangers,Rangers,New York,NYR,NYR,NY Rangers
19,20,29,New Jersey Devils,Devils,New Jersey,NJD,NJD,New Jersey
20,21,32,Ottawa Senators,Senators,Ottawa,OTT,OTT,Ottawa
21,22,35,Minnesota Wild,Wild,Minnesota,MIN,MIN,Minnesota
22,23,41,Los Angeles Kings,Kings,Los Angeles,LAK,LAK,Los Angeles
23,24,43,Arizona Coyotes,Coyotes,Arizona,ARI,ARI,Arizona
24,25,45,Florida Panthers,Panthers,Florida,FLA,FLA,Florida
25,26,46,Dallas Stars,Stars,Dallas,DAL,DAL,Dallas
26,27,50,Phoenix Coyotes,Coyotes,Phoenix,PHX,PHX,Phoenix
27,28,51,New York Islanders,Islanders,New York,NYI,NYI,NY Islanders
28,29,52,Columbus Blue Jackets,Blue Jackets,Columbus,CBJ,CBJ,Columbus
29,30,53,Vancouver Canucks,Canucks,Vancouver,VAN,VAN,Vancouver
30,31,59,Vegas Golden Knights,Golden Knights,Vegas,VGK,VGK,Vegas
31,32,66,Carolina Hurricanes,Hurricanes,Carolina,CAR,CAR,Carolina
32,33,11366,Atlanta Thrashers,Thrashers,Atlanta,ATL,ATL,Atlanta

In [3]:
#Import NHL Competition Data and Display Head
NHL_Competition=pd.read_csv("NHL_competition.csv")
NHL_Competition.head()

   Unnamed: 0  comp_id  year  type                     name  tz  start  end
0           1        1  2013     2  2013 NHL Regular Season  ET    NaN  NaN
1           2        2  2017     2  2017 NHL Regular Season  ET    NaN  NaN
2           3     2453  2013     3         2013 NHL Playoff  ET    NaN  NaN
3           4     2541  2017     3         2017 NHL Playoff  ET    NaN  NaN
4           5     2661  2012     2  2012 NHL Regular Season  ET    NaN  NaN

In [4]:
#Import NHL Game Data and Display Head
NHL_Game=pd.read_csv("NHL_game.csv")
NHL_Game.head()

   X  gid  comp_id        date  ascore  hscore  period  status home_away  tid
0  1   37        2   10/7/2017     NaN     NaN     NaN     NaN      away   25
1  2   67        2   10/9/2017     NaN     NaN     NaN     NaN      away   29
2  3  154        1  10/14/2013     NaN     NaN     NaN     NaN      away   29
3  4  278        1  10/24/2013     NaN     NaN     NaN     NaN      away   53
4  5  291        1  10/25/2013     NaN     NaN     NaN     NaN      away    5

In [5]:
#Import NHL PPPK Data and Display Head
NHL_PPPK=pd.read_csv("pp.pk.ppgf.csv")
NHL_PPPK.head()

  tricode   pp   pk  ppgf  competition_name
0     ANA   35   27   9.0  2010 NHL Playoff
1     BOS  126  116  22.0  2010 NHL Playoff
2     BUF   48   46  13.0  2010 NHL Playoff
3     CHI   27   39   6.0  2010 NHL Playoff
4     DET   59   55   6.0  2010 NHL Playoff

## Part 2 - Descriptive and Summary Analyses

## Part 3 - Correlation Analyses

## Uncomment this Section once your assignment is complete

In [ ]:
#Save Dataframes as .csv files
#NHL_Game.to_csv("NHL_Game2.csv", index=False)
#NHL_Team_Stats.to_csv("NHL_Team_Stats.csv", index=False)
#NHL_Team_R_Stats.to_csv("NHL_Team_R_Stats.csv", index=False)