# I. Coding Run Expectancy Dataset (2017)

In [1]:
#Load packages
import pandas as pd
import numpy as np

In [2]:
# Read in MLBAM Data for 2017

MLBAM17 = pd.read_csv("MLBAM17.csv")

# drop column with no relevant information
MLBAM17.drop(['Unnamed: 0'], axis=1, inplace=True)
MLBAM17

,inning,batterId,pitcherId,event,x,y,ab_num,timestamp,stand,throws,...,fielderId,gameId,isPA,isAB,isHit,isBIP,our.x,our.y,r,theta
0,1,458731,502042,Flyout,65.59,123.50,1,2017-04-02 17:12:18,L,R,...,605480.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-148.267814,188.423160,239.763700,2.237490
1,1,596142,502042,Groundout,128.19,193.88,2,2017-04-02 17:15:42,R,R,...,502042.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,7.961190,12.777835,15.055020,1.013603
2,1,595885,502042,Walk,NaN,NaN,3,2017-04-02 17:16:48,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
3,1,407812,502042,Groundout,153.48,157.29,4,2017-04-02 17:19:09,R,R,...,543543.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,71.076710,104.094437,126.045827,0.971701
4,1,572816,547888,Single,140.75,73.31,5,2017-04-02 17:24:43,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,39.306818,313.680887,316.134030,1.446138
5,1,595281,547888,Double,103.34,100.63,6,2017-04-02 17:25:58,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-54.056234,245.499156,251.380015,1.787527
6,1,446334,547888,Sac Fly,NaN,NaN,7,2017-04-02 17:29:16,R,R,...,592450.0,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
7,1,543543,547888,Single,145.19,182.67,8,2017-04-02 17:30:57,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,50.387597,40.754307,64.806045,0.680094
8,1,519306,547888,Walk,NaN,NaN,9,2017-04-02 17:32:58,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
9,1,489149,547888,Single,130.06,87.56,10,2017-04-02 17:35:40,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,12.628095,278.117575,278.404121,1.525422
10,1,542921,547888,Lineout,145.42,79.78,11,2017-04-02 17:38:22,R,R,...,453056.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,50.961602,297.533896,301.866699,1.401162
11,1,605480,547888,Strikeout,NaN,NaN,12,2017-04-02 17:39:11,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,False,NaN,NaN,NaN,NaN
12,2,453056,502042,Flyout,51.93,139.48,13,2017-04-02 17:42:51,L,R,...,605480.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-182.358679,148.542337,235.201008,2.458036
13,2,516770,502042,Single,136.17,148.63,14,2017-04-02 17:45:25,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,27.876645,125.706948,128.760802,1.352569
14,2,452104,502042,Single,77.13,131.84,15,2017-04-02 17:49:10,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-119.467770,167.609264,205.828602,2.190045
15,2,592450,502042,Double,43.57,100.85,16,2017-04-02 17:52:18,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-203.222489,244.950108,318.276508,2.263356
16,2,591720,502042,Groundout,141.26,163.90,17,2017-04-02 17:53:27,R,R,...,543543.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,40.579610,87.598052,96.540787,1.136980
17,2,458731,502042,Groundout,145.84,163.40,18,2017-04-02 17:55:01,L,R,...,543543.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,52.009783,88.845887,102.949547,1.041186
18,2,519083,547888,Groundout,101.05,171.54,19,2017-04-02 17:59:49,R,R,...,452104.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-59.771320,68.531125,90.934734,2.288026
19,2,572816,547888,Strikeout,NaN,NaN,20,2017-04-02 18:01:08,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,False,NaN,NaN,NaN,NaN
20,2,595281,547888,Walk,NaN,NaN,21,2017-04-02 18:02:02,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
21,2,446334,547888,Home Run,27.76,96.72,22,2017-04-02 18:05:12,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,False,-242.679047,255.257229,352.206435,2.330939
22,2,543543,547888,Flyout,98.88,79.61,23,2017-04-02 18:06:59,L,R,...,453056.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-65.186926,297.958160,305.005574,1.786182
23,3,596142,502042,Groundout,109.20,157.80,24,2017-04-02 18:10:44,R,R,...,542921.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-39.431602,102.821645,110.123303,1.936994
24,3,595885,502042,Flyout,49.65,139.47,25,2017-04-02 18:12:38,L,R,...,605480.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-188.048809,148.567294,239.655160,2.472950
25,3,407812,502042,Strikeout,NaN,NaN,26,2017-04-02 18:13:19,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,False,NaN,NaN,NaN,NaN
26,3,519306,547888,Strikeout,NaN,NaN,27,2017-04-02 18:17:09,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,False,NaN,NaN,NaN,NaN
27,3,489149,547888,Home Run,166.48,31.20,28,2017-04-02 18:19:55,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,False,103.520433,418.773593,431.378954,1.328456
28,3,542921,547888,Double,41.50,111.48,29,2017-04-02 18:21:32,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-208.388528,218.421125,301.883366,2.332693
29,3,605480,547888,Single,124.47,196.99,30,2017-04-02 18:23:27,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-1.322706,5.016299,5.187755,1.828610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185565,6,594807,642239,Double,24.25,89.88,40,2017-10-01 20:47:52,R,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,-251.438852,272.327619,370.653246,2.316334
185566,6,553993,642239,Single,175.04,140.69,41,2017-10-01 20:49:15,R,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,124.883376,145.522576,191.762034,0.861577
185567,6,571697,642239,Single,185.48,109.50,42,2017-10-01 20:53:24,L,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,150.938182,223.362554,269.579608,0.976529
185568,6,640447,642239,Lineout,111.41,144.47,43,2017-10-01 20:54:11,R,L,...,608365.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,-33.916169,136.088939,140.251581,1.815041
185569,6,595453,642239,Strikeout,NaN,NaN,44,2017-10-01 20:54:53,R,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185570,6,543089,608652,Flyout,85.10,110.52,45,2017-10-01 20:59:01,R,R,...,594807.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,-99.577273,220.816969,242.230814,1.994439
185571,6,546991,608652,Groundout,149.48,150.57,46,2017-10-01 21:00:02,R,R,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,61.094026,120.865346,135.428623,1.102781
185572,6,502273,608652,Groundout,149.48,149.55,47,2017-10-01 21:02:02,L,R,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,61.094026,123.410931,137.705257,1.111120
185573,7,623182,570240,Groundout,127.68,191.63,48,2017-10-01 21:06:19,R,R,...,570240.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,6.688398,18.393095,19.571424,1.222025
185574,7,571740,570240,Lineout,105.83,60.24,49,2017-10-01 21:07:03,L,R,...,445055.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,-47.842013,346.299307,349.588427,1.708080
185575,7,572227,570240,Strikeout,NaN,NaN,50,2017-10-01 21:08:25,R,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185576,7,450314,593974,Strikeout,NaN,NaN,51,2017-10-01 21:13:01,R,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185577,7,570240,593974,Strikeout,NaN,NaN,52,2017-10-01 21:16:57,R,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185578,7,656941,593974,Groundout,148.47,149.55,53,2017-10-01 21:17:12,L,L,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,58.573398,123.410931,136.605640,1.127657
185579,8,458015,570240,Double,76.68,55.67,54,2017-10-01 21:18:52,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,-120.590822,357.704523,377.484665,1.895955
185580,8,594807,570240,Strikeout,NaN,NaN,55,2017-10-01 21:21:39,R,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185581,8,553993,570240,Flyout,131.59,53.12,56,2017-10-01 21:24:30,R,R,...,445055.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,16.446472,364.068484,364.439772,1.525653
185582,8,571697,570240,Strikeout,NaN,NaN,57,2017-10-01 21:25:29,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185583,8,605170,594992,Strikeout,NaN,NaN,58,2017-10-01 21:29:32,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185584,8,600303,594992,Strikeout,NaN,NaN,59,2017-10-01 21:31:54,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185585,8,664023,594992,Strikeout,NaN,NaN,60,2017-10-01 21:34:41,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185586,9,640447,596027,Flyout,192.57,97.34,61,2017-10-01 21:38:47,R,R,...,518792.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,168.632489,253.709913,304.640175,0.984180
185587,9,595453,596027,Strikeout,NaN,NaN,62,2017-10-01 21:39:35,R,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185588,9,608385,596027,Single,185.98,100.38,63,2017-10-01 21:41:30,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,152.186017,246.123073,289.373722,1.017006
185589,9,571740,596027,Walk,NaN,NaN,64,2017-10-01 21:42:52,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,False,False,False,NaN,NaN,NaN,NaN
185590,9,572227,596027,Runner Out,NaN,NaN,65,2017-10-01 21:44:19,R,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,False,False,False,False,NaN,NaN,NaN,NaN
185591,9,543089,628452,Groundout,142.89,147.02,66,2017-10-01 21:49:41,R,R,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,44.647554,129.724978,137.193200,1.239324
185592,9,546991,628452,Home Run,119.91,21.25,67,2017-10-01 21:50:11,R,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,False,-12.702965,443.605519,443.787361,1.599424
185593,9,502273,628452,Groundout,127.01,201.44,68,2017-10-01 21:51:15,L,R,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,5.016299,-6.089437,7.889518,-0.881728
185594,9,450314,628452,Groundout,126.83,200.86,69,2017-10-01 21:51:48,L,R,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,4.567078,-4.641948,6.511980,-0.793528

In [3]:
# Keep relevant columns
RE17 = MLBAM17[['batterName','batterId','event', 'start1B', 'start2B', 'start3B', 'end1B', 'end2B', 'end3B',\
                   'startOuts','endOuts','runsFuture','runsOnPlay','outsInInning',\
                   'stand', 'throws','venueId', 'stadium', 'batterPos']].copy()

display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,12,Tropicana Field,LF
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,12,Tropicana Field,C
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,2,0,0,3,L,R,12,Tropicana Field,1B
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,0,3,0,3,L,R,12,Tropicana Field,DH
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,0,3,0,3,L,R,12,Tropicana Field,CF
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,1,3,1,3,R,R,12,Tropicana Field,3B
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,1,2,0,3,L,R,12,Tropicana Field,2B
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,1,2,0,3,R,R,12,Tropicana Field,RF
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,1,2,2,3,L,R,12,Tropicana Field,1B
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,2,0,0,3,R,R,12,Tropicana Field,SS
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,12,Tropicana Field,LF
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,2,0,3,L,R,12,Tropicana Field,CF
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,1,2,0,3,R,R,12,Tropicana Field,2B
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,1,2,0,3,L,R,12,Tropicana Field,3B
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,1,2,1,3,R,R,12,Tropicana Field,RF
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,2,1,1,3,R,R,12,Tropicana Field,SS
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,3,0,0,3,L,R,12,Tropicana Field,LF
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,2,0,3,R,R,12,Tropicana Field,C
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,2,0,3,L,R,12,Tropicana Field,DH
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,2,2,0,3,L,R,12,Tropicana Field,CF
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,2,2,2,3,R,R,12,Tropicana Field,3B
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,12,Tropicana Field,2B
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,12,Tropicana Field,C
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,12,Tropicana Field,1B
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,2,0,3,R,R,12,Tropicana Field,RF
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,2,1,3,L,R,12,Tropicana Field,1B
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,1,1,0,3,R,R,12,Tropicana Field,SS
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,1,1,1,3,L,R,12,Tropicana Field,LF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185565,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,1,1,0,3,R,L,17,Wrigley Field,LF
185566,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,1,1,0,3,R,L,17,Wrigley Field,3B
185567,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,1,1,1,3,L,L,17,Wrigley Field,2B
185568,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,2,0,0,3,R,L,17,Wrigley Field,RF
185569,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,17,Wrigley Field,UN
185570,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,17,Wrigley Field,UN
185571,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,17,Wrigley Field,UN
185572,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,UN
185573,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,17,Wrigley Field,UN
185574,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,CF
185575,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN
185576,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,17,Wrigley Field,LF
185577,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,17,Wrigley Field,UN
185578,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,L,17,Wrigley Field,UN
185579,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,0,0,0,3,L,R,17,Wrigley Field,1B
185580,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,1,0,0,3,R,R,17,Wrigley Field,LF
185581,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,2,0,0,3,R,R,17,Wrigley Field,3B
185582,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,2B
185583,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,17,Wrigley Field,UN
185584,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN
185585,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,UN
185586,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,17,Wrigley Field,RF
185587,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,17,Wrigley Field,UN
185588,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,2,0,0,3,L,R,17,Wrigley Field,UN
185589,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,2,0,0,3,L,R,17,Wrigley Field,CF
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,3,R,R,17,Wrigley Field,UN
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,3,R,R,17,Wrigley Field,UN
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,LF

In [4]:
# Create indicator variables to determine whether base is occupied prior to plate appearance
# Create starting base out state for plate appearance
RE17['Start1'] = np.where(pd.isnull(RE17['start1B']),0,1)
RE17['Start2'] = np.where(pd.isnull(RE17['start2B']),0,1)
RE17['Start3'] = np.where(pd.isnull(RE17['start3B']),0,1)
RE17['Start_State'] = (RE17['Start1'].astype(str) + RE17['Start2'].astype(str) + RE17['Start3'].astype(str)+\
                          " " + RE17['startOuts'].astype(str))
RE17

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,L,R,12,Tropicana Field,LF,0,0,0,000 0
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,R,12,Tropicana Field,C,0,0,0,000 1
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,3,L,R,12,Tropicana Field,1B,0,0,0,000 2
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,3,R,R,12,Tropicana Field,DH,1,0,0,100 2
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,3,L,R,12,Tropicana Field,DH,0,0,0,000 0
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,3,L,R,12,Tropicana Field,CF,1,0,0,100 0
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,3,R,R,12,Tropicana Field,3B,0,1,1,011 0
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,3,L,R,12,Tropicana Field,2B,0,1,0,010 1
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,3,R,R,12,Tropicana Field,RF,1,0,1,101 1
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,3,L,R,12,Tropicana Field,1B,1,1,1,111 1
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,3,R,R,12,Tropicana Field,SS,1,1,0,110 1
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,3,L,R,12,Tropicana Field,LF,1,1,0,110 2
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,L,R,12,Tropicana Field,CF,0,0,0,000 0
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,3,R,R,12,Tropicana Field,2B,0,0,0,000 1
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,3,L,R,12,Tropicana Field,3B,1,0,0,100 1
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,3,R,R,12,Tropicana Field,RF,1,1,0,110 1
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,3,R,R,12,Tropicana Field,SS,0,1,1,011 1
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,3,L,R,12,Tropicana Field,LF,0,0,1,001 2
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,12,Tropicana Field,C,0,0,0,000 0
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,L,R,12,Tropicana Field,DH,0,0,0,000 1
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,3,L,R,12,Tropicana Field,CF,0,0,0,000 2
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,3,R,R,12,Tropicana Field,3B,1,0,0,100 2
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,L,R,12,Tropicana Field,2B,0,0,0,000 2
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,12,Tropicana Field,C,0,0,0,000 0
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,L,R,12,Tropicana Field,1B,0,0,0,000 1
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,R,R,12,Tropicana Field,DH,0,0,0,000 2
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,12,Tropicana Field,RF,0,0,0,000 0
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,L,R,12,Tropicana Field,1B,0,0,0,000 1
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,3,R,R,12,Tropicana Field,SS,0,0,0,000 1
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,3,L,R,12,Tropicana Field,LF,0,1,0,010 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185565,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,3,R,L,17,Wrigley Field,LF,0,0,0,000 1
185566,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,3,R,L,17,Wrigley Field,3B,0,1,0,010 1
185567,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,3,L,L,17,Wrigley Field,2B,1,0,1,101 1
185568,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,3,R,L,17,Wrigley Field,RF,1,1,0,110 1
185569,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,3,R,L,17,Wrigley Field,UN,1,1,0,110 2
185570,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 0
185571,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 1
185572,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,L,R,17,Wrigley Field,UN,0,0,0,000 2
185573,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 0
185574,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,L,R,17,Wrigley Field,CF,0,0,0,000 1
185575,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 2
185576,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,L,17,Wrigley Field,LF,0,0,0,000 0
185577,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,L,17,Wrigley Field,UN,0,0,0,000 1
185578,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,L,L,17,Wrigley Field,UN,0,0,0,000 2
185579,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,3,L,R,17,Wrigley Field,1B,0,0,0,000 0
185580,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,3,R,R,17,Wrigley Field,LF,0,1,0,010 0
185581,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,3,R,R,17,Wrigley Field,3B,0,1,0,010 1
185582,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,3,L,R,17,Wrigley Field,2B,0,1,0,010 2
185583,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,L,R,17,Wrigley Field,UN,0,0,0,000 0
185584,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,L,R,17,Wrigley Field,UN,0,0,0,000 1
185585,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,L,R,17,Wrigley Field,UN,0,0,0,000 2
185586,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,17,Wrigley Field,RF,0,0,0,000 0
185587,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 1
185588,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,3,L,R,17,Wrigley Field,UN,0,0,0,000 2
185589,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,3,L,R,17,Wrigley Field,CF,1,0,0,100 2
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,3,R,R,17,Wrigley Field,UN,1,1,0,110 2
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 0
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 1
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,L,R,17,Wrigley Field,UN,0,0,0,000 1
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,L,R,17,Wrigley Field,LF,0,0,0,000 2

In [5]:
# Create indicator variables to determine whether base is occupied after plate appearance
# Create ending base out state for plate appearance
RE17['End1'] = np.where(pd.isnull(RE17['end1B']),0,1)
RE17['End2'] = np.where(pd.isnull(RE17['end2B']),0,1)
RE17['End3'] = np.where(pd.isnull(RE17['end3B']),0,1)
RE17['End_State'] = (RE17['End1'].astype(str) + RE17['End2'].astype(str) + RE17['End3'].astype(str)+\
                          " " + RE17['endOuts'].astype(str))
RE17

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,LF,0,0,0,000 0,0,0,0,000 1
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,C,0,0,0,000 1,0,0,0,000 2
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,Tropicana Field,1B,0,0,0,000 2,1,0,0,100 2
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,DH,1,0,0,100 2,0,0,0,000 3
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,Tropicana Field,DH,0,0,0,000 0,1,0,0,100 0
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,Tropicana Field,CF,1,0,0,100 0,0,1,1,011 0
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,Tropicana Field,3B,0,1,1,011 0,0,1,0,010 1
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,Tropicana Field,2B,0,1,0,010 1,1,0,1,101 1
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,Tropicana Field,RF,1,0,1,101 1,1,1,1,111 1
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,Tropicana Field,1B,1,1,1,111 1,1,1,0,110 1
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,Tropicana Field,SS,1,1,0,110 1,1,1,0,110 2
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,Tropicana Field,LF,1,1,0,110 2,0,0,0,000 3
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,CF,0,0,0,000 0,0,0,0,000 1
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,Tropicana Field,2B,0,0,0,000 1,1,0,0,100 1
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,Tropicana Field,3B,1,0,0,100 1,1,1,0,110 1
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,Tropicana Field,RF,1,1,0,110 1,0,1,1,011 1
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,Tropicana Field,SS,0,1,1,011 1,0,0,1,001 2
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,Tropicana Field,LF,0,0,1,001 2,0,0,0,000 3
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,C,0,0,0,000 0,0,0,0,000 1
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,DH,0,0,0,000 1,0,0,0,000 2
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,Tropicana Field,CF,0,0,0,000 2,1,0,0,100 2
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,3B,1,0,0,100 2,0,0,0,000 2
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,2B,0,0,0,000 2,0,0,0,000 3
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,C,0,0,0,000 0,0,0,0,000 1
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,1B,0,0,0,000 1,0,0,0,000 2
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,DH,0,0,0,000 2,0,0,0,000 3
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,RF,0,0,0,000 0,0,0,0,000 1
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,1B,0,0,0,000 1,0,0,0,000 1
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,Tropicana Field,SS,0,0,0,000 1,0,1,0,010 1
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,Tropicana Field,LF,0,1,0,010 1,0,1,0,010 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185565,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,Wrigley Field,LF,0,0,0,000 1,0,1,0,010 1
185566,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,Wrigley Field,3B,0,1,0,010 1,1,0,1,101 1
185567,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,Wrigley Field,2B,1,0,1,101 1,1,1,0,110 1
185568,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,Wrigley Field,RF,1,1,0,110 1,1,1,0,110 2
185569,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3
185570,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185571,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185572,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185573,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185574,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,CF,0,0,0,000 1,0,0,0,000 2
185575,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185576,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,LF,0,0,0,000 0,0,0,0,000 1
185577,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185578,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185579,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,Wrigley Field,1B,0,0,0,000 0,0,1,0,010 0
185580,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,Wrigley Field,LF,0,1,0,010 0,0,1,0,010 1
185581,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,Wrigley Field,3B,0,1,0,010 1,0,1,0,010 2
185582,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,Wrigley Field,2B,0,1,0,010 2,0,0,0,000 3
185583,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185584,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185585,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185586,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,RF,0,0,0,000 0,0,0,0,000 1
185587,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185588,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,1,0,0,100 2
185589,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,Wrigley Field,CF,1,0,0,100 2,1,1,0,110 2
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 1
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,LF,0,0,0,000 2,0,0,0,000 3

In [6]:
# Restrict data to plays where either there is a change in state or runs scored and innings that had exactly 3 outs
RE17 = RE17[((RE17.Start_State != RE17.End_State) | (RE17.runsOnPlay > 0)) & (RE17.outsInInning == 3)]
display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,LF,0,0,0,000 0,0,0,0,000 1
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,C,0,0,0,000 1,0,0,0,000 2
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,Tropicana Field,1B,0,0,0,000 2,1,0,0,100 2
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,DH,1,0,0,100 2,0,0,0,000 3
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,Tropicana Field,DH,0,0,0,000 0,1,0,0,100 0
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,Tropicana Field,CF,1,0,0,100 0,0,1,1,011 0
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,Tropicana Field,3B,0,1,1,011 0,0,1,0,010 1
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,Tropicana Field,2B,0,1,0,010 1,1,0,1,101 1
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,Tropicana Field,RF,1,0,1,101 1,1,1,1,111 1
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,Tropicana Field,1B,1,1,1,111 1,1,1,0,110 1
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,Tropicana Field,SS,1,1,0,110 1,1,1,0,110 2
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,Tropicana Field,LF,1,1,0,110 2,0,0,0,000 3
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,CF,0,0,0,000 0,0,0,0,000 1
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,Tropicana Field,2B,0,0,0,000 1,1,0,0,100 1
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,Tropicana Field,3B,1,0,0,100 1,1,1,0,110 1
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,Tropicana Field,RF,1,1,0,110 1,0,1,1,011 1
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,Tropicana Field,SS,0,1,1,011 1,0,0,1,001 2
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,Tropicana Field,LF,0,0,1,001 2,0,0,0,000 3
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,C,0,0,0,000 0,0,0,0,000 1
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,DH,0,0,0,000 1,0,0,0,000 2
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,Tropicana Field,CF,0,0,0,000 2,1,0,0,100 2
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,3B,1,0,0,100 2,0,0,0,000 2
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,2B,0,0,0,000 2,0,0,0,000 3
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,C,0,0,0,000 0,0,0,0,000 1
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,1B,0,0,0,000 1,0,0,0,000 2
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,DH,0,0,0,000 2,0,0,0,000 3
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,RF,0,0,0,000 0,0,0,0,000 1
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,1B,0,0,0,000 1,0,0,0,000 1
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,Tropicana Field,SS,0,0,0,000 1,0,1,0,010 1
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,Tropicana Field,LF,0,1,0,010 1,0,1,0,010 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185565,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,Wrigley Field,LF,0,0,0,000 1,0,1,0,010 1
185566,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,Wrigley Field,3B,0,1,0,010 1,1,0,1,101 1
185567,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,Wrigley Field,2B,1,0,1,101 1,1,1,0,110 1
185568,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,Wrigley Field,RF,1,1,0,110 1,1,1,0,110 2
185569,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3
185570,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185571,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185572,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185573,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185574,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,CF,0,0,0,000 1,0,0,0,000 2
185575,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185576,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,LF,0,0,0,000 0,0,0,0,000 1
185577,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185578,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185579,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,Wrigley Field,1B,0,0,0,000 0,0,1,0,010 0
185580,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,Wrigley Field,LF,0,1,0,010 0,0,1,0,010 1
185581,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,Wrigley Field,3B,0,1,0,010 1,0,1,0,010 2
185582,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,Wrigley Field,2B,0,1,0,010 2,0,0,0,000 3
185583,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185584,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185585,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185586,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,RF,0,0,0,000 0,0,0,0,000 1
185587,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185588,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,1,0,0,100 2
185589,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,Wrigley Field,CF,1,0,0,100 2,1,1,0,110 2
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 1
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,LF,0,0,0,000 2,0,0,0,000 3

In [7]:
# Calculate run expectancy by starting state and merge into play by play data
Start_RunExp = RE17.groupby(['Start_State'])['runsFuture'].mean().reset_index().rename(columns={'runsFuture':'Start_RE'})
RE17 = pd.merge(RE17, Start_RunExp, on=['Start_State'], how='left')
display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,LF,0,0,0,000 0,0,0,0,000 1,0.516375
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,C,0,0,0,000 1,0,0,0,000 2,0.272176
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,1B,0,0,0,000 2,1,0,0,100 2,0.108038
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,DH,1,0,0,100 2,0,0,0,000 3,0.225365
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,DH,0,0,0,000 0,1,0,0,100 0,0.516375
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,CF,1,0,0,100 0,0,1,1,011 0,0.912921
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,3B,0,1,1,011 0,0,1,0,010 1,2.051376
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,2B,0,1,0,010 1,1,0,1,101 1,0.711650
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,RF,1,0,1,101 1,1,1,1,111 1,1.215306
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,1B,1,1,1,111 1,1,1,0,110 1,1.635608
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,SS,1,1,0,110 1,1,1,0,110 2,0.947424
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,LF,1,1,0,110 2,0,0,0,000 3,0.449782
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,CF,0,0,0,000 0,0,0,0,000 1,0.516375
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,2B,0,0,0,000 1,1,0,0,100 1,0.272176
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,3B,1,0,0,100 1,1,1,0,110 1,0.524904
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,RF,1,1,0,110 1,0,1,1,011 1,0.947424
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,SS,0,1,1,011 1,0,0,1,001 2,1.517131
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,LF,0,0,1,001 2,0,0,0,000 3,0.381186
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,C,0,0,0,000 0,0,0,0,000 1,0.516375
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,DH,0,0,0,000 1,0,0,0,000 2,0.272176
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,CF,0,0,0,000 2,1,0,0,100 2,0.108038
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,3B,1,0,0,100 2,0,0,0,000 2,0.225365
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,2B,0,0,0,000 2,0,0,0,000 3,0.108038
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,C,0,0,0,000 0,0,0,0,000 1,0.516375
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,1B,0,0,0,000 1,0,0,0,000 2,0.272176
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,DH,0,0,0,000 2,0,0,0,000 3,0.108038
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,RF,0,0,0,000 0,0,0,0,000 1,0.516375
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,1B,0,0,0,000 1,0,0,0,000 1,0.272176
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,SS,0,0,0,000 1,0,1,0,010 1,0.272176
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,LF,0,1,0,010 1,0,1,0,010 1,0.711650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184721,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,LF,0,0,0,000 1,0,1,0,010 1,0.272176
184722,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,3B,0,1,0,010 1,1,0,1,101 1,0.711650
184723,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,2B,1,0,1,101 1,1,1,0,110 1,1.215306
184724,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,RF,1,1,0,110 1,1,1,0,110 2,0.947424
184725,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,UN,1,1,0,110 2,0,0,0,000 3,0.449782
184726,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,UN,0,0,0,000 0,0,0,0,000 1,0.516375
184727,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,UN,0,0,0,000 1,0,0,0,000 2,0.272176
184728,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,UN,0,0,0,000 2,0,0,0,000 3,0.108038
184729,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,UN,0,0,0,000 0,0,0,0,000 1,0.516375
184730,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,CF,0,0,0,000 1,0,0,0,000 2,0.272176
184731,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,UN,0,0,0,000 2,0,0,0,000 3,0.108038
184732,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,LF,0,0,0,000 0,0,0,0,000 1,0.516375
184733,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,UN,0,0,0,000 1,0,0,0,000 2,0.272176
184734,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,UN,0,0,0,000 2,0,0,0,000 3,0.108038
184735,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,1B,0,0,0,000 0,0,1,0,010 0,0.516375
184736,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,LF,0,1,0,010 0,0,1,0,010 1,1.154829
184737,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,3B,0,1,0,010 1,0,1,0,010 2,0.711650
184738,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,2B,0,1,0,010 2,0,0,0,000 3,0.336702
184739,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,UN,0,0,0,000 0,0,0,0,000 1,0.516375
184740,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,UN,0,0,0,000 1,0,0,0,000 2,0.272176
184741,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,UN,0,0,0,000 2,0,0,0,000 3,0.108038
184742,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,RF,0,0,0,000 0,0,0,0,000 1,0.516375
184743,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,UN,0,0,0,000 1,0,0,0,000 2,0.272176
184744,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,UN,0,0,0,000 2,1,0,0,100 2,0.108038
184745,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,CF,1,0,0,100 2,1,1,0,110 2,0.225365
184746,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,UN,1,1,0,110 2,0,0,0,000 3,0.449782
184747,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,UN,0,0,0,000 0,0,0,0,000 1,0.516375
184748,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,UN,0,0,0,000 1,0,0,0,000 1,0.272176
184749,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,UN,0,0,0,000 1,0,0,0,000 2,0.272176
184750,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,LF,0,0,0,000 2,0,0,0,000 3,0.108038

In [8]:
# Code run expectancy values by end state using start state run expectancy including end states with 3 outs
Base_State_3 = [pd.Series(['000 3', 0], index=Start_RunExp.columns),
                pd.Series(['001 3', 0], index=Start_RunExp.columns),
                pd.Series(['010 3', 0], index=Start_RunExp.columns),
                pd.Series(['011 3', 0], index=Start_RunExp.columns),
                pd.Series(['100 3', 0], index=Start_RunExp.columns),
                pd.Series(['101 3', 0], index=Start_RunExp.columns),
                pd.Series(['110 3', 0], index=Start_RunExp.columns),
                pd.Series(['111 3', 0], index=Start_RunExp.columns)]

Start_RunExp = Start_RunExp.append(Base_State_3, ignore_index=True)

End_RunExp = Start_RunExp.rename(columns={'Start_State':'End_State', 'Start_RE':'End_RE'})

display(End_RunExp)

   End_State    End_RE
0      000 0  0.516375
1      000 1  0.272176
2      000 2  0.108038
3      001 0  1.436482
4      001 1  0.953586
5      001 2  0.381186
6      010 0  1.154829
7      010 1  0.711650
8      010 2  0.336702
9      011 0  2.051376
10     011 1  1.517131
11     011 2  0.601763
12     100 0  0.912921
13     100 1  0.524904
14     100 2  0.225365
15     101 0  1.838889
16     101 1  1.215306
17     101 2  0.496480
18     110 0  1.509497
19     110 1  0.947424
20     110 2  0.449782
21     111 0  2.241581
22     111 1  1.635608
23     111 2  0.804609
24     000 3  0.000000
25     001 3  0.000000
26     010 3  0.000000
27     011 3  0.000000
28     100 3  0.000000
29     101 3  0.000000
30     110 3  0.000000
31     111 3  0.000000

In [9]:
# Merge into play by play data
RE17 = pd.merge(RE17, End_RunExp, on=['End_State'], how='left')
display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,0,0,0,000 2,1,0,0,100 2,0.108038,0.225365
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,1,0,0,100 2,0,0,0,000 3,0.225365,0.000000
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,0,0,0,000 0,1,0,0,100 0,0.516375,0.912921
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,1,0,0,100 0,0,1,1,011 0,0.912921,2.051376
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,0,1,1,011 0,0,1,0,010 1,2.051376,0.711650
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,0,1,0,010 1,1,0,1,101 1,0.711650,1.215306
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,1,0,1,101 1,1,1,1,111 1,1.215306,1.635608
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,1,1,1,111 1,1,1,0,110 1,1.635608,0.947424
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,1,1,0,110 1,1,1,0,110 2,0.947424,0.449782
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,1,1,0,110 2,0,0,0,000 3,0.449782,0.000000
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,0,0,0,000 1,1,0,0,100 1,0.272176,0.524904
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,1,0,0,100 1,1,1,0,110 1,0.524904,0.947424
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,1,1,0,110 1,0,1,1,011 1,0.947424,1.517131
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,0,1,1,011 1,0,0,1,001 2,1.517131,0.381186
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,0,0,1,001 2,0,0,0,000 3,0.381186,0.000000
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,0,0,0,000 2,1,0,0,100 2,0.108038,0.225365
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,1,0,0,100 2,0,0,0,000 2,0.225365,0.108038
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 1,0.272176,0.272176
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,0,0,0,000 1,0,1,0,010 1,0.272176,0.711650
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,0,1,0,010 1,0,1,0,010 1,0.711650,0.711650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184721,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,0,0,0,000 1,0,1,0,010 1,0.272176,0.711650
184722,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,0,1,0,010 1,1,0,1,101 1,0.711650,1.215306
184723,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,1,0,1,101 1,1,1,0,110 1,1.215306,0.947424
184724,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,1,1,0,110 1,1,1,0,110 2,0.947424,0.449782
184725,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,1,1,0,110 2,0,0,0,000 3,0.449782,0.000000
184726,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184727,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184728,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000
184729,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184730,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184731,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000
184732,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184733,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184734,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000
184735,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,0,0,0,000 0,0,1,0,010 0,0.516375,1.154829
184736,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,0,1,0,010 0,0,1,0,010 1,1.154829,0.711650
184737,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,0,1,0,010 1,0,1,0,010 2,0.711650,0.336702
184738,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,0,1,0,010 2,0,0,0,000 3,0.336702,0.000000
184739,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184740,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184741,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000
184742,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184743,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184744,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,0,0,0,000 2,1,0,0,100 2,0.108038,0.225365
184745,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,1,0,0,100 2,1,1,0,110 2,0.225365,0.449782
184746,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,1,1,0,110 2,0,0,0,000 3,0.449782,0.000000
184747,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184748,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 1,0.272176,0.272176
184749,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184750,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000

In [10]:
# Run Value of each event

RE17['Run_Value'] = RE17['runsOnPlay'] + RE17['End_RE'] - RE17['Start_RE']

display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE,Run_Value
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.108038,0.225365,0.117327
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 3,0.225365,0.000000,-0.225365
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,0,0,000 0,1,0,0,100 0,0.516375,0.912921,0.396546
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,0,0,100 0,0,1,1,011 0,0.912921,2.051376,1.138455
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,1,1,011 0,0,1,0,010 1,2.051376,0.711650,-0.339727
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,1,0,010 1,1,0,1,101 1,0.711650,1.215306,0.503657
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,0,1,101 1,1,1,1,111 1,1.215306,1.635608,0.420302
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,1,1,111 1,1,1,0,110 1,1.635608,0.947424,1.311816
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,1,0,110 1,1,1,0,110 2,0.947424,0.449782,-0.497642
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 3,0.449782,0.000000,-0.449782
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.272176,0.524904,0.252728
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,0,0,100 1,1,1,0,110 1,0.524904,0.947424,0.422520
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,1,0,110 1,0,1,1,011 1,0.947424,1.517131,1.569707
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,1,1,011 1,0,0,1,001 2,1.517131,0.381186,-0.135945
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,0,1,001 2,0,0,0,000 3,0.381186,0.000000,-0.381186
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.108038,0.225365,0.117327
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 2,0.225365,0.108038,1.882673
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 1,0.272176,0.272176,1.000000
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,0,0,000 1,0,1,0,010 1,0.272176,0.711650,0.439473
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,1,0,010 1,0,1,0,010 1,0.711650,0.711650,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184721,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,0,0,000 1,0,1,0,010 1,0.272176,0.711650,0.439473
184722,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,1,0,010 1,1,0,1,101 1,0.711650,1.215306,0.503657
184723,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,0,1,101 1,1,1,0,110 1,1.215306,0.947424,0.732118
184724,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,1,0,110 1,1,1,0,110 2,0.947424,0.449782,-0.497642
184725,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 3,0.449782,0.000000,-0.449782
184726,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184727,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184728,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
184729,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184730,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184731,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
184732,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184733,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184734,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
184735,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,0,0,000 0,0,1,0,010 0,0.516375,1.154829,0.638454
184736,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,1,0,010 0,0,1,0,010 1,1.154829,0.711650,-0.443179
184737,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,1,0,010 1,0,1,0,010 2,0.711650,0.336702,-0.374947
184738,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,1,0,010 2,0,0,0,000 3,0.336702,0.000000,-0.336702
184739,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184740,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184741,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
184742,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184743,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184744,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.108038,0.225365,0.117327
184745,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,0,0,100 2,1,1,0,110 2,0.225365,0.449782,0.224418
184746,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 3,0.449782,0.000000,-0.449782
184747,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184748,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 1,0.272176,0.272176,1.000000
184749,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184750,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038

In [11]:
# Calculate percent of plate appearances resulting in flyouts
RE17['Count'] = 1
Flyout = RE17[RE17['event']=='Flyout']
sum(Flyout['Count'])/sum(RE17['Count'])

0.10697100421648598

In [12]:
RE17_BLoad = RE17[(RE17['Start_State'] == "111 0")|(RE17['Start_State'] == "111 1")|(RE17['Start_State'] == "111 2")]
RE17_BLoad

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE,Run_Value,Count
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,1,111 1,1,1,0,110 1,1.635608,0.947424,1.311816,1
57,"Sanchez, G",596142,Groundout,458731.0,452104.0,516770.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
72,"Miller, B",543543,Strikeout,446334.0,595281.0,572816.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
76,Carter,474892,Sac Fly,543305.0,592450.0,452104.0,543305.0,592450.0,NaN,0,...,1,111 0,1,1,0,110 1,2.241581,0.947424,-0.294157,1
150,Posey,457763,Flyout,452254.0,474832.0,452655.0,452254.0,474832.0,452655.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
151,Crawford,543063,Forceout,452254.0,474832.0,452655.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
198,"Martinez, C",593372,Grounded Into DP,545341.0,543939.0,425877.0,NaN,NaN,NaN,1,...,1,111 1,0,0,0,000 3,1.635608,0.000000,-1.635608,1
212,Bryant,592178,Flyout,656941.0,595879.0,575929.0,656941.0,595879.0,575929.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
213,Rizzo,519203,Flyout,656941.0,595879.0,575929.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
288,Werth,150029,Strikeout,475582.0,502517.0,547180.0,475582.0,502517.0,547180.0,0,...,1,111 0,1,1,1,111 1,2.241581,1.635608,-0.605973,1
289,Drew,452220,Grounded Into DP,475582.0,502517.0,547180.0,NaN,NaN,NaN,1,...,1,111 1,0,0,0,000 3,1.635608,0.000000,-1.635608,1
349,Granderson,434158,Sac Fly,493316.0,452678.0,408314.0,493316.0,452678.0,NaN,1,...,1,111 1,1,1,0,110 2,1.635608,0.449782,-0.185826,1
351,Bruce,457803,Walk,435522.0,493316.0,452678.0,457803.0,435522.0,493316.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
352,Duda,446263,Double,457803.0,435522.0,493316.0,NaN,446263.0,NaN,2,...,1,111 2,0,1,0,010 2,0.804609,0.336702,2.532093,1
419,"Marte, S",516782,Sac Fly,624428.0,474568.0,543281.0,624428.0,474568.0,NaN,1,...,1,111 1,1,1,0,110 2,1.635608,0.449782,-0.185826,1
477,Villar,542340,Double,542583.0,606115.0,542908.0,NaN,542340.0,542583.0,0,...,1,111 0,0,1,1,011 0,2.241581,2.051376,1.809795,1
494,Blackmon,453568,Forceout,506924.0,547172.0,448602.0,453568.0,NaN,547172.0,1,...,1,111 1,1,0,1,101 2,1.635608,0.496480,-0.139128,1
553,Bautista,430832,Pop Out,518626.0,485567.0,607680.0,518626.0,485567.0,607680.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
554,Morales,434778,Walk,518626.0,485567.0,607680.0,434778.0,518626.0,485567.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
555,Tulowitzki,453064,Groundout,434778.0,518626.0,485567.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
653,Grossman,543257,Walk,572821.0,596146.0,593871.0,543257.0,572821.0,596146.0,1,...,1,111 1,1,1,1,111 1,1.635608,1.635608,1.000000,1
654,Buxton,621439,Strikeout,543257.0,572821.0,596146.0,543257.0,572821.0,596146.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
655,Mauer,408045,Walk,543257.0,572821.0,596146.0,408045.0,543257.0,572821.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
656,Sano,593934,Walk,408045.0,543257.0,572821.0,593934.0,408045.0,543257.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
657,"Castro, J",488771,Single,593934.0,408045.0,543257.0,488771.0,NaN,593934.0,2,...,1,111 2,1,0,1,101 2,0.804609,0.496480,1.691871,1
693,Hamilton,571740,Sac Fly,444857.0,571466.0,446359.0,444857.0,571466.0,NaN,0,...,1,111 0,1,1,0,110 1,2.241581,0.947424,-0.294157,1
702,Cozart,446359,Flyout,594988.0,553993.0,594807.0,594988.0,553993.0,594807.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
703,Barnhart,571466,Flyout,594988.0,553993.0,594807.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
709,Saunders,459431,Groundout,596748.0,546318.0,435062.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
772,Pederson,592626,Home Run,523253.0,408236.0,457759.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 2,0.804609,0.108038,3.303429,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183885,"Gonzalez, G",461829,Strikeout,446308.0,150029.0,475582.0,446308.0,150029.0,475582.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
183886,Turner,607208,Groundout,446308.0,150029.0,475582.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
183903,Turner,607208,Strikeout,446653.0,572191.0,446308.0,446653.0,572191.0,446308.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
183904,Harper,547180,Groundout,446653.0,572191.0,446308.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
183934,Moroff,621559,Walk,656669.0,605137.0,516782.0,621559.0,656669.0,605137.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
183935,Stallings,607732,Single,621559.0,656669.0,605137.0,607732.0,621559.0,656669.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
183936,"Frazier, A",624428,Lineout,607732.0,621559.0,656669.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
183941,Lobaton,446653,Grounded Into DP,572191.0,435062.0,457477.0,NaN,NaN,NaN,1,...,1,111 1,0,0,0,000 3,1.635608,0.000000,-1.635608,1
183957,Blash,518466,Grounded Into DP,605486.0,500208.0,641319.0,NaN,NaN,NaN,1,...,1,111 1,0,0,0,000 3,1.635608,0.000000,-1.635608,1
184134,Pennington,460060,Sac Fly,543068.0,453203.0,472528.0,NaN,543068.0,453203.0,0,...,1,111 0,0,1,1,011 1,2.241581,1.517131,0.275550,1
184136,Graterol,492802,Sac Fly,592230.0,543068.0,453203.0,592230.0,543068.0,NaN,1,...,1,111 1,1,1,0,110 2,1.635608,0.449782,-0.185826,1
184296,Plouffe,461858,Walk,519306.0,489149.0,446334.0,461858.0,519306.0,489149.0,1,...,1,111 1,1,1,1,111 1,1.635608,1.635608,1.000000,1
184297,Casali,592200,Walk,461858.0,519306.0,489149.0,592200.0,461858.0,519306.0,1,...,1,111 1,1,1,1,111 1,1.635608,1.635608,1.000000,1
184298,"Smith, M",605480,Sac Fly,592200.0,461858.0,519306.0,592200.0,NaN,461858.0,1,...,1,111 1,1,0,1,101 2,1.635608,0.496480,-0.139128,1
184300,Bourjos,488721,Flyout,621002.0,592200.0,461858.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
184312,Encarnacion,429665,Lineout,608070.0,543401.0,596019.0,608070.0,543401.0,596019.0,0,...,1,111 0,1,1,1,111 1,2.241581,1.635608,-0.605973,1
184313,Bruce,457803,Single,608070.0,543401.0,596019.0,457803.0,NaN,608070.0,1,...,1,111 1,1,0,1,101 1,1.635608,1.215306,1.579698,1
184360,Brantley,488726,Groundout,608070.0,656185.0,650490.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
184461,"Hernandez, K",571771,Sac Fly,641355.0,457759.0,608369.0,641355.0,NaN,457759.0,1,...,1,111 1,1,0,1,101 2,1.635608,0.496480,-0.139128,1
184483,Culberson,518586,Walk,572204.0,592626.0,518735.0,518586.0,572204.0,592626.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
184484,Maeda,628317,Groundout,518586.0,572204.0,592626.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
184559,Cain,456715,Forceout,460077.0,444876.0,593528.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
184575,Negron,502117,Single,453923.0,489267.0,543302.0,502117.0,453923.0,489267.0,0,...,1,111 0,1,1,1,111 0,2.241581,2.241581,1.000000,1
184576,"Vargas, I",545121,Forceout,502117.0,453923.0,489267.0,545121.0,NaN,453923.0,0,...,1,111 0,1,0,1,101 1,2.241581,1.215306,-0.026275,1
184598,Rosales,489267,Forceout,543302.0,518614.0,592273.0,489267.0,543302.0,518614.0,0,...,1,111 0,1,1,1,111 1,2.241581,1.635608,-0.605973,1
184599,"Blanco, G",453923,Forceout,489267.0,543302.0,518614.0,453923.0,NaN,543302.0,1,...,1,111 1,1,0,1,101 2,1.635608,0.496480,-0.139128,1
184616,Aguilar,542583,Sac Fly,519346.0,542340.0,519299.0,519346.0,NaN,542340.0,0,...,1,111 0,1,0,1,101 1,2.241581,1.215306,-0.026275,1
184672,DeJong,657557,Strikeout,642423.0,608348.0,594824.0,642423.0,608348.0,594824.0,0,...,1,111 0,1,1,1,111 1,2.241581,1.635608,-0.605973,1
184673,Valera,591971,Pop Out,642423.0,608348.0,594824.0,642423.0,608348.0,594824.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
184674,"Mejia, A",622270,Groundout,642423.0,608348.0,594824.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1

In [13]:
# Strikeouts by position
Strikeouts = RE17[RE17['event'] == "Strikeout"]
Strikeouts.groupby(['batterPos'])['Count'].sum().reset_index()

   batterPos  Count
0         1B   4399
1         2B   3710
2         3B   4023
3          C   4090
4         CF   4374
5         DH   2354
6         LF   4317
7          P   1872
8         PH      1
9         RF   4386
10        SS   3734
11        UN   2594

In [ ]:
# Strikeouts by position
Strikeouts = RE17[RE17['event'] == "Strikeout"]
Strikeouts.groupby(['batterPos'])['Count'].sum().reset_index()